version: '3.7'
services:
  points:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - shopping_db
  shopping_db:
    image: postgres:latest
    container_name: "shopping_db"
    ports:
      - "5432:5432"
    volumes:
      - shopping_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
volumes:
  shopping_dbdata:
