# Server config
server:
  port: ${PORT:8086}

# Spring config
spring:
  application:
    name: shopping-service
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# Ribbon config
ribbon:
  eureka:
    enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 2s
      failureRateThreshold: 30
      eventConsumerBufferSize: 10

  instances:
    backendA:
      baseConfig: default
